queue_rules:
  - name: default
    conditions:
      - check-success=SweetAlert2

pull_request_rules:
  - name: automatic merge on CI success and review - Dependabot
    conditions:
      - check-success=SweetAlert2
      - author~=^dependabot(|-preview)\[bot\]$
      - base=main
    actions:
      queue:
        name: default